### ISSUE TITLE
rails console issue

### ISSUE THREAD

**Issue by sergiomarrocoli** [learn-co-curriculum/rails-create-action-readme#11]
i can get rails to work with sqlite2 by dropping the rails version and specifying the sqlite3 version '~> 1.3.6'. 
But rails console won't work, with this error:

/usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.7.1/lib/rails/commands/console.rb:20:in `block in parse_arguments'
: invalid option: -b (OptionParser::InvalidOption)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
