### ISSUE TITLE
No Routes Written, despite instructions

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/rails-create-action-readme#13]
Hey there. In the ReadMe it says, `We've already got the route and our form created. If you go to /posts/new, fill out the form, and submit it, you'll get the error shown below.` but there are no routes written. Just update that or add the route code to add.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
