### ISSUE TITLE
Lab requires strong params, when it shouldn't at this stage

### ISSUE THREAD

**Issue by rossmawd** [learn-co-curriculum/rails-create-action-readme#14]
(according to the subsequent 'Strong Params' lab

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
