### ISSUE TITLE
"We've already got the route and our form created"...form, yes...route? no.

### ISSUE THREAD

**Issue by EvanRatzlaff** [learn-co-curriculum/rails-create-action-readme#15]
The lab says there is route but it is missing. 

resources :posts, only: [:index, :new, :show, :create] 

is not there. You have to add it yourself for all tests to pass.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
