### ISSUE TITLE
No routes in lab and gives an error that is not mentioned on readme

### ISSUE THREAD

**Issue by gzavaglia** [learn-co-curriculum/rails-create-action-readme#16]
The lab is not complete since the routes.rb is blank. I had to add 
```resources :posts, only: [:index, :show, :new, :create]```
to make it pass

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
