### ISSUE TITLE
missing routes in route.rb

### ISSUE THREAD

**Issue by audefaucheux** [learn-co-curriculum/rails-create-action-readme#17]
It seems that no route was added to route.rb in the config file despite the below sentence in the readme

"As long as the form is routed to the create method we've written (in config/routes.rb), we'll be able to initialize a new instance of Post, grab those input values from params, assign them the post instance attributes and save the instance to our database."

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
