### ISSUE TITLE
solution a little too advanced for this stage?

### ISSUE THREAD

**Issue by bmolina-nyc** [learn-co-curriculum/rails-create-action-readme#7]
Just thought i'd comment here - the way the lab was solved in the answer is super different from the way the rails lessons have ramped us up.  Obvs theres a million ways to do stuff it just felt like it was a bit more shortcuts than one can infer at the beginning stages of rails.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
