### ISSUE TITLE
The post path for the create method in posts controller only passed when an 's' was added to the end of 'post'

### ISSUE THREAD

**Issue by samsonyuwono** [learn-co-curriculum/rails-create-action-readme#8]
Below is what you have for this readme and wont pass unless post_path is changed to posts_path

def create
  @post = Post.new
  @post.title = params[:title]
  @post.description = params[:description]
  @post.save
  redirect_to post_path(@post)
end

**Comment by gj** [comment]
Hi @samsonyuwono !

`posts_path` and `post_path` are helpers for different routes. The relevant section from README.md:
>In this refactored `create` action, we're following the convention of redirecting to the new resource's `show` page. It stands to reason that a user who submits a new post would then like to view the successfully-created post. With that being said, the page flow is not set in stone, and we could've redirected the `create` action to the `index` action just as easily.
