### ISSUE TITLE
Using @post instead of post in the redirect.

### ISSUE THREAD

**Issue by Sillhouette** [learn-co-curriculum/rails-create-action-readme#9]
```
def create
  @post = Post.new
  @post.title = params[:title]
  @post.description = params[:description]
  @post.save
  redirect_to post_path(@post)
end
```

The redirect in this line should be changed to 'post' from @post. Otherwise the specs fail with this error:

```
form
  shows a new form that submits content and redirects and prints out params (FAILED - 1)

Failures:

  1) form shows a new form that submits content and redirects and prints out params
     Failure/Error: redirect_to post_path(@post)

     ActionController::UrlGenerationError:
       No route matches {:action=>"show", :controller=>"posts", :id=>nil} missing required keys: [:id]
```

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
